Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("João e Maria");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Agora eu era o herói");
Console.WriteLine("E o meu cavalo só falava inglês");
Console.WriteLine("A noiva do cowboy era você além das outras três");
Console.WriteLine("Eu enfrentava os batalhões, os alemães e seus canhões");
Console.WriteLine("Guardava o meu bodoque e ensaiava o rock para as matinês");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Agora eu era o rei");
Console.WriteLine("Era o bedel e era também juiz");
Console.WriteLine("E pela minha lei a gente era obrigada a ser feli");
Console.WriteLine("E você era a princesa que eu fiz coroar");
Console.WriteLine("E era tão linda de se admirar");
Console.WriteLine("Que andava nua pelo meu país");
Console.WriteLine("");
Console.WriteLine("Não, não fuja não");
Console.WriteLine("Finja que agora eu era o seu brinquedo");
Console.WriteLine("Eu era o seu pião, o seu bicho preferido");
Console.WriteLine("Vem, me dê a mão, a gente agora já não tinha medo");
Console.WriteLine("No tempo da maldade acho que a gente nem tinha nascido");
Console.WriteLine("");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("Agora era fatal que o faz-de-conta terminasse assim");
Console.WriteLine("Pra lá deste quintal era uma noite que não tem mais fim");
Console.WriteLine("Pois você sumiu no mundo sem me avisar");
Console.WriteLine("E agora eu era um louco a perguntar");
Console.WriteLine("O que que a vida vai fazer de mim?");